//	******************************************************************************
//	
//  SALVADOR VILLALON PRACTICE
//	exception.h
// 
//  An exception to throw when the index has gone out of bounds
//	
//	********************************************************************************


#include "stdafx.h"

// The preprocessor examines the code before actual compilation of code begins and 
// resolves all these directives before any code is actually generated by 
// regular statements.
// Why do we need this?
// This is necesarry so the file is not included multiple times, 

//#ifndef EXCEPTION_H
//#define EXCEPTION_H



class IndexOutOfBoundsException
{
};

//#endif